### ISSUE TITLE
Add toBinary method to encode decoded-rawProto object to binary

### ISSUE THREAD

**Issue by labac-p** [konsumer/rawproto#25]
🙇🏻

**Comment by konsumer** [comment]
This should be in `proto..buffer`, right?

```js
const tree = new RawProto([0x1a, 0x03, 0x08, 0x96, 0x01])
console.log(tree.buffer)
// ArrayBuffer { [Uint8Contents]: <1a 03 08 96 01>, byteLength: 5 }
```

It should just match what you inputtted to it, anyway.

**Comment by konsumer** [comment]
Ok, I added something just for you, since it seems like a nice use-case anyway, and it gave me a chance to test out the `toProto` function, which needed more testing, anyway.

You'll need to install `rawproto@1.0.2` (latest) and then check out [this test](https://github.com/konsumer/rawproto/blob/master/test/decodeencode.test.js). Basically, I have an unknown binary, I analyze it with rawproto, create a proto SDL from that, then use [protobufjs](https://www.npmjs.com/package/protobufjs) with the SDL to encode it. In actual usecase, you'd want to edit the generated proto to look more like [this](https://github.com/konsumer/rawproto/blob/master/test/test.proto), which has better field-names/types and known enums (instead of just setting them all to `int32`.)

Let me know if that helps.

**Comment by labac-p** [comment]
Thank you for your thoughtful reply. With your suggestion I have found the solution to my problem.
